services:
  nexzap_postgres:
    image: postgres:17-alpine3.21
    environment:
      - POSTGRES_USER=nexzap
      - POSTGRES_PASSWORD=nexzap
      - POSTGRES_DB=nexzap
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexzap"]
      interval: 10s
      timeout: 5s
      retries: 5
