services:
  nexzap:
    image: nexzap:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexzap.rule=Host(`nexzap.app`)"
      - "traefik.http.routers.nexzap.entrypoints=websecure"
      - "traefik.http.routers.nexzap.tls.certresolver=myresolver"
      - "traefik.http.services.nexzap.loadbalancer.server.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      update_config:
        order: start-first
    depends_on:
      - nexzap_postgres
    networks:
      - traefik

  nexzap_postgres:
    image: postgres:17-alpine3.21
    environment:
      - POSTGRES_USER=nexzap
      - POSTGRES_PASSWORD=nexzap
      - POSTGRES_DB=nexzap
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexzap"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - traefik
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
networks:
  traefik:
    external: true
