version: "3"

tasks:
  tailwind:
    desc: Build the style.css from classes found in templ files
    cmd: tailwindcss -i ./static/css/input.css -o ./static/css/style.css --minify
    sources:
      - ./templates/**/*.templ
    generates:
      - ./static/css/style.css

  templ:
    desc: Generate the templ files
    cmd: templ generate
    sources:
      - ./templates/**/*.templ
    generates:
      - ./templates/**/*_templ.go

  sqlc:
    desc: Generate Go code from raw SQL
    cmd: sqlc generate
    sources:
      - ./internal/db/queries/*.sql
    generates:
      - ./internal/db/generated/*.sql.go

  build:
    desc: Build the Go binary
    cmd: go build -o ./tmp/main ./cmd/nexzap/main.go
    deps:
      - templ
      - sqlc
      - tailwind
    sources:
      - ./go.mod
      - ./go.sum
      - ./cmd/**/*.go
      - ./internal/**/*.go
      - ./templates/**/*_templ.go
      - ./static/css/style.css
      - ./internal/db/migrations/*.sql
    generates:
      - ./tmp/main

  run:
    desc: Run the built binary
    deps:
      - build
    cmd: ./tmp/main

  default:
    desc: Run the full build and start the program
    deps:
      - run
